services:
  - type: web
    name: rider-management-api
    env: node
    branch: main
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: MONGO_URI
        sync: false