const express=require("express");
const cors=require("cors");
const connectDB=require("./config/db");
const app=express();
app.use(cors());
app.use(express.json());
connectDB();
app.use("/api/riders",require("./routes/riders"));
app.use("/api/trips",require("./routes/trips"));
app.use("/api/payments",require("./routes/payments"));
app.use("/api/payouts",require("./routes/payouts"));
app.get("/",(req,res)=>res.send("Rider Management API running"));
app.listen(process.env.PORT||5000);